### ISSUE TITLE
firmware-esp32-GENERIC_C3_USB.bin

### ISSUE THREAD

**Issue by pvanha** [glenn20/micropython-espnow-images#14]
When flashing my 2Mb AT ESP32-C3-32S-Kit with the above FW, the terminal provides the below (rolling) error message:

esptool.py --chip ESP32-C3 --port COM5 --baud 115200 write_flash -z --flash_mode dio --flash_freq 40m --flash_size 2MB 0x0 C:\...\firmware-esp32-GENERIC_C3_USB.bin

//
Build:Feb 7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x403d125a
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fcd6100,len:0xe3c
load:0x403ce000,len:0x6dc
load:0x403d0000,len:0x28c4
SHA-256 comparison failed:
Calculated: fd3f46f452876f51561ede25b86befaf844a521837fbba339ebcf5eb724ffcc1
Expected: cc1b2eebb938fa995d080d3c3a72466af2b3fb7ab3811755ee14ffb7cd234d0c
Attempting to boot anyway...
entry 0x403ce000
E (53) flash_parts: partition 3 invalid - offset 0x200000 size 0x200000 exceeds flash chip size 0x20000ESP-ROM:esp32c3-api1-20210207
//

Does this ring a bell to you? Any solution you know of?
Many thanks in advance,
P

**Comment by glenn20** [comment]
Thanks for the bug report. I'm afraid I don't have a C3 device, but I do have S2 USB devices and these flash fine for me. You could try with "--flash_size detect" and see if that provides any more useful information.

Are you able to flash a vanilla micropython image with the same command?
