### ISSUE TITLE
Webrepl  not working on 8266 esp01

### ISSUE THREAD

**Issue by Andrew-Rayner** [glenn20/micropython-espnow-images#21]
Hi Glenn

Sorry to bother.
Wondering have you tested webrepl
It loads but the esp01 8266 goes into a loop never to recover requiring a reload of the os.  Strange..

**Comment by glenn20** [comment]
Thanks for following up. I just tested webrepl on my two esp8266 devices (GENERIC and GENERIC_1M). webrepl is working fine on both my devices. However, I don't have an ESP01 device to test.

**Comment by glenn20** [comment]
@Andrew-Rayner  - Thanks for reporting this issue.

if you are still having problems with webrepl on esp8266, let me know. Else I will close this Issue in the next few weeks as it is working for my tests with recent images.

**Comment by Andrew-Rayner** [comment]
Sorry delay,  I noticed the new repositories and tried them and appears to work using   2022-07-09   assumed you had fixed it  when dropped back in to look  as part of other bits.

Many Thanks,  :-)
