### ISSUE TITLE
ESP32 ESPNow generic urequests

### ISSUE THREAD

**Issue by davefes** [glenn20/micropython-espnow-images#29]
Is there some reason, other than image size, that urequests is not part of this image?.

**Comment by glenn20** [comment]
Ah... yes. I discovered that the default build process for micropython images is NOT used for the release images (they use a slightly different board definition which includes urequests, mqtt and some other library modules frozen into the image). Now that I know about it, I will fix that in my next round of image builds. In the meantime you have to install your own urequests.py (or better - urequests.mpy) onto the filesystem of the image.

Note that a recent commit to the master branch removes this difference, so the default build is the same as the release build.

**Comment by davefes** [comment]
I also noticed yesterday that mqtt.simple and mqtt.robust weren't in there as well so reverted to the standard v1.19.1 for a project.
Thank you.
