### ISSUE TITLE
Ok this is my issue but love to hear a comment

### ISSUE THREAD

**Issue by Andrew-Rayner** [glenn20/micropython-espnow-images#34]
Hi Glenn

Just a question I cant work out the memory management on these esp8266.

I bought 2  4Gig ones and rest are 1Gig,  Using 22-07-09  and works fine,  but I cant squeeze any more code on the 4G I get to about 10K of code,  and it keeps  breaking lack of space,  appears a little more on the 4G,  but not much.

I do regular Mem.free  and it cruises around 13 - 12000 before I do a GC.Collect  to get it back for a few cycles.

(Yes the code is tight I cant actual remove much more to clean it up)  and yes I do have lots  loaded,  WEBREPL, WIFIMANAGER WEBPAGES and ESPNOW Meshed,   
but I expected the 4G to at least give me 20K of code lines before dropping me like a  flea ridden dog  LOL 

Any reason you can think why hitting this at only 10K of actual code is there something im missing 

NB I am (not loading the 1G Image using the  non specific image  that is good for 2g and 4g right  :-))

Just asking not really expecting,  odd as got the 4g just for this reason :-) 

Cheers

**Comment by glenn20** [comment]
@Andrew-Rayner  : That's a 4M device (4G would be pretty impressive :-). This refers to the amount of flash on the device - ie. the space to hold the micropython image and the device filesystem. The RAM is the same on all esp8266 devices (as far as I am aware).

From wikipedia (and the spec sheet):
```
32 KiB instruction RAM
32 KiB instruction cache RAM
80 KiB user-data RAM
16 KiB ETS system-data RAM
```

Unfortunately, the micropython system consumes a fair bit of available RAM - leaving typically less than 40kB of RAM for users. `import micropython; micropython.mem_info()`. If you want to, you can build a smaller custom micropython image by excluding a bunch of features that you don't need and you'll have a bit more RAM available, depeending on what you can sacrifice.

If you want more RAM you really need an ESP32 :-). And if you want really large amounts of RAM you can get a lot of ESP32 devices with 4, 8, 16 MB of PSRAM included. It's fun to try and exhaust the memory on those devices.
