### ISSUE TITLE
ESPnow bug in sending

### ISSUE THREAD

**Issue by danish1963** [glenn20/micropython-espnow-images#7]
I'm trying to use Espnow on esp8266. When i try to send str(7) or '7' the esp8266 reboot, I can send all other number with out failure, is there a bug in the firmware. 
The firmware is : firmware-esp8266-GENERIC.bin ....MicroPython v1.17-12-g26e539a1b on 2021-09-03; ESP module with ESP8266

The code i use:
import network
import time
from esp import espnow

# A WLAN interface must be active to send()/recv()
w0 = network.WLAN(network.STA_IF)  # Or network.AP_IF
w0.active(True)

e = espnow.ESPNow()
e.init()

peer = b'\xf4\xcf\xa2\xd1\x10\x7b' # put your reciever mac adress
e.add_peer(peer)

e.send(peer,"Starting...",True)       # Send to all peers

while True:
    e.send(peer, "My Name", True)
    e.send(peer, '7', True)     # the string '7' reboot the esp8266? all other string (I try)  works.
    time.sleep(2)

**Comment by glenn20** [comment]
A little more debugging info... sending 'e', 'f', 'j', 'n', 'r', 's',  'w', 'y'' also causes a reboot.

These are all micropython 'interned' QSTR strings and the strings that all crash return buffer addresses in the same range (0x4028XXXX) and all others have an address in the range 0x3ffeXXXX, so it may be some memory mapping issue for the Espressif esp_now_send() call.
I'll keep investigating, but if anyone has a clue - please let me know.

**Comment by glenn20** [comment]
By tweaking my build environment I was able to fit the esp8266 code into the text size limit with the bug fix.

New ESP8266 images are available in the 20211020_espnow-g20-v1.17-g26f058583 folder. These images pass all micropython tests including my espnow multi-tests.

Please test and let me know if there are any problems. If not I will close this issue in a week or so.

Thanks again for the bug report - was a surprising bug. It seems that esp_now_send() is trying to write to the read-only memory passed to it - which it should not.

**Comment by glenn20** [comment]
Excellent. Closing now. Reopen if it resurfaces or there are any other related problems.
